# Generated by Django 2.0.6 on 2018-07-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180703_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job',
            new_name='company',
        ),
    ]
